```yaml
name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: seu-usuario
          outputs: dist/github-contribution-grid-snake.svg

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Snake
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
